- hosts: all
  become: true
  tasks:
    - name: Remove python-is-python2 https://www.kali.org/docs/general-use/python3-transition/
      ansible.builtin.package:
        name: python-is-python2
        state: absent

    - name: Set python to python3
      ansible.builtin.package:
        name: python-is-python3
        state: present

    - name: Set timezone to Europe/London
      timezone:
        name: Europe/London

    - name: Remove slow kali repo
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent

    - name: Add faster kali package repo
      apt_repository:
        repo: deb https://mirrors.dotsrc.org/kali kali-rolling main non-free contrib
        state: present
        update_cache: true

    - name: Prevent grab update
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - grub-common
        - grub-pc
        - grub-pc-bin
        - grub2-common

    - name: Update and upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
      when: lookup('ansible.builtin.env', 'KALIGRANT_UPGRADE') == 'true'

    - name: Disable autostart of light-locker to avoid screen lock
      ansible.builtin.file:
        path: /etc/xdg/autostart/light-locker.desktop
        state: absent

    - name: Kill light-locker process to avoid screen lock
      ansible.builtin.shell: pkill light-locker; exit 0

    - name: Create lightdm.conf
      vars:
        autologin_user: vagrant
      ansible.builtin.template:
        src: lightdm.conf.j2
        dest: /etc/lightdm/lightdm.conf
        owner: root
        group: root
        mode: '0644'
